export const TRADABLE_STOCKS = [
  { ticker: "7203", name: "トヨタ自動車" },
  { ticker: "6758", name: "ソニーグループ" },
  { ticker: "9984", name: "ソフトバンクグループ" },
  { ticker: "7974", name: "任天堂" },
  { ticker: "9432", name: "日本電信電話" },
  { ticker: "7201", name: "日産自動車" },
  { ticker: "6702", name: "富士通" },
  { ticker: "8001", name: "伊藤忠商事" },
  { ticker: "9983", name: "ファーストリテイリング" },
  { ticker: "6981", name: "村田製作所" },
  { ticker: "7267", name: "ホンダ" },
  { ticker: "6752", name: "パナソニック" },
  { ticker: "8035", name: "東京エレクトロン" },
  { ticker: "6861", name: "キーエンス" },
  { ticker: "4063", name: "信越化学工業" },
];
